# Generated by Django 4.0.3 on 2022-12-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='Read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messages',
            name='Read',
            field=models.BooleanField(default=False),
        ),
    ]
