# Generated by Django 4.0.3 on 2022-12-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_files_read_messages_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='Send',
            field=models.BooleanField(default=False),
        ),
    ]
