# Generated by Django 4.0.3 on 2022-12-09 06:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_files_send'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='Read',
        ),
        migrations.RemoveField(
            model_name='files',
            name='Send',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='Read',
        ),
        migrations.AddField(
            model_name='messages',
            name='ReadUsers',
            field=models.ManyToManyField(related_name='read_messgages', to=settings.AUTH_USER_MODEL),
        ),
    ]
