# Generated by Django 4.0.3 on 2022-12-09 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_files_read_remove_files_send_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='ReadUsers',
        ),
    ]
