# Generated by Django 4.0.3 on 2022-12-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_messages_readusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='filetype',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
