# Generated by Django 4.0.3 on 2022-12-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_files_filetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='icon',
            field=models.ImageField(blank=True, upload_to='icons/'),
        ),
    ]
