# Generated by Django 4.0.3 on 2022-12-18 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_icons'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Icons',
        ),
    ]
