# Generated by Django 4.0.3 on 2022-12-18 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_delete_icons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='icon',
        ),
    ]
